version: "3.8"

volumes:
  mysql-data:
  go-module-cache:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace
      - go-module-cache:/go/pkg
    command: sleep infinity
    network_mode: service:db  

  db:
    image: mysql:5.7.21
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: devpassword
      MYSQL_ROOT_HOST: '%'
    volumes:
      - mysql-data:/var/lib/mysql

   adminer:
    image: adminer # https://hub.docker.com/_/adminer
    restart: always
    network_mode: service:db
    environment:
    - ADMINER_DESIGN=pappu687
    - ADMINER_DEFAULT_SERVER=127.0.0.1 

   redis:
    image: redis:7.0
    restart: unless-stopped
    network_mode: service:db          
